remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: [Fault Finder: Predictive Analytics for Power Outage Causes]
description: [Utilizing a sophisticated machine learning model, we leverage key indicators such as Gross State Product, population affected, climate region, and month to unravel the complex patterns and accurately predict the root cause of a power outage.]